spring:
  application:
    name: lms-lti-3rdpartyprovisioning
  session:
    store-type: none
  config.import: optional:${app.fullFilePath}/${app.overridesFileName}, optional:${app.fullFilePath}/security.properties, classpath:canvas.properties, optional:classpath:git.properties, optional:classpath:email.properties, optional:classpath:denodo.properties, classpath:lti-registrations.properties, optional:classpath:derdack.properties
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
      jadira:
        usertype:
          autoRegisterUserTypes: true
  datasource:
    url: ${lms.db.url}
    username: ${lms.db.user}
    password: ${lms.db.password}
    type: ${lms.db.poolType}
  cloud.vault.enabled: false
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: ${oauth.tokenprovider.url}/.well-known/jwks.json
#      client:
#        registration:
#          uaa:
#            provider: uaa
#            client-id: ${oauth.tokenprovider.clientId}
#            client-secret: ${oauth.tokenprovider.clientSecret}
#            authorization-grant-type: client_credentials
#            client-authentication-method: client_secret_post
#        provider:
#          uaa:
#            token-uri: ${oauth.tokenprovider.accessTokenUri}

  rabbitmq:
    addresses: ${lms.rabbitmq.address.${app.env}}
    username: ${lms.rabbitmq.username.${app.env}}
    password: ${lms.rabbitmq.password.${app.env}}
    virtualHost: ${lms.rabbitmq.virtualHost.${app.env}}
    listener.simple:
      acknowledge-mode: manual
      missing-queues-fatal: false
      retry:
        enabled: true
        initial-interval: 3s
        max-attempts: 3
        max-interval: 10s
        multiplier: 2
deptprov:
  version: @app.version@
  env: ${app.env}
  prd:
    guestAccountCreationUrl: https://eaa.apps.iu.edu
    canvasServiceName: CanvasProd
    expandServiceName: ExpandProd
  stg:
    guestAccountCreationUrl: https://eaa-stg.apps-test.iu.edu
    canvasServiceName: CanvasTest
    expandServiceName: ExpandBeta
  reg:
    guestAccountCreationUrl: https://eaa-stg.apps-test.iu.edu
    canvasServiceName: CanvasBeta
    expandServiceName: ExpandBeta
  snd:
    guestAccountCreationUrl: https://eaa-stg.apps-test.iu.edu
    canvasServiceName: CanvasSand
    expandServiceName: ExpandBeta
  dev:
    guestAccountCreationUrl: https://eaa-stg.apps-test.iu.edu
    canvasServiceName: CanvasBeta
    expandServiceName: ExpandBeta
  ci:
    guestAccountCreationUrl: https://eaa-stg.apps-test.iu.edu
    canvasServiceName: CanvasBeta
    expandServiceName: ExpandBeta
  guestAccountCreationUrl: ${deptprov.${app.env}.guestAccountCreationUrl}
  canvasServiceName: ${deptprov.${app.env}.canvasServiceName}
  expandServiceName: ${deptprov.${app.env}.expandServiceName}
  backgroundQueueName: deptprov_queue_${app.env}
  defaultBatchNotificationEmail: iu-uits-es-ess-lms-notify@exchange.iu.edu

expand:
  baseUrl: ${expand.baseUrl.${app.env}}
  baseApiUrl: ${expand.baseUrl}/api/v1
  token: ${expand.token.${app.env}}

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 30m

app:
  env: dev
  fullFilePath: file:/usr/src/app/config
  overridesFileName: overrides.properties

management:
  endpoint.lms.enabled: true
  endpoints.web.exposure.include: health,lms
  health.redis.enabled: false
  info.java.enabled: true

springdoc:
  api-docs.enabled: false
  swagger-ui.enabled: false

---

spring:
  config.activate.on-profile: redis-session
  session:
    store-type: redis
    redis.namespace: deptprov-@app.version@:session
management.health.redis.enabled: true

---

spring:
  config:
    activate.on-profile: vault
    import:
      - vault://${spring.cloud.vault.kv.backend}/managed/${spring.cloud.vault.kv.application-name}/${app.env}/oauth
      - vault://${spring.cloud.vault.kv.backend}/application
      - vault://${spring.cloud.vault.kv.backend}/${spring.cloud.vault.kv.application-name}/all
      - vault://${spring.cloud.vault.kv.backend}/${spring.cloud.vault.kv.application-name}/${app.env}
  cloud.vault:
    enabled: true
    config:
      lifecycle.lease-endpoints: leases
    generic:
      enabled: false
    kv:
      enabled: true
      backend: ua-vpit/enterprise-systems/lms/kv
      application-name: lmslti3rdpartyprovisioning

---

spring:
  config:
    activate.on-profile: swagger
springdoc:
  api-docs:
    enabled: true
    path: /api/v3/api-docs
  cache.disabled: true
  packagesToScan: edu.iu.uits.lms.provisioning.controller.rest
  swagger-ui:
    enabled: false
    disable-swagger-default-url: true
    path: /api/swagger-ui.html
    # Setting supportedSubmitMethods to an empty list is what turns off the "try it out" button
    #    supportedSubmitMethods:
    oauth:
      clientId: ${spring.security.oauth2.client.registration.uaa.client-id}
  oAuthFlow:
    authorizationUrl: ${spring.security.oauth2.client.provider.uaa.authorization-uri}
    tokenUrl: ${spring.security.oauth2.client.provider.uaa.token-uri}