spring:
  application:
    name: lms-lti-3rdpartyprovisioning
  profiles:
    active: redis
  session:
    store-type: none
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
      jadira:
        usertype:
          autoRegisterUserTypes: true

  datasource:
    driverClassName: ${lti.db.driverClass}
    url: ${lti.db.url}
    username: ${lti.db.user}
    password: ${lti.db.password}
server:
  servlet:
    session:
      cookie:
        name: LMSSESSION
security:
  oauth2:
    client:
      userAuthorizationUri: ${oauth.tokenprovider.url}/oauth/authorize
      accessTokenUri: ${oauth.tokenprovider.url}/oauth/token
      clientId: ${oauth.tokenprovider.clientId}
      clientSecret: ${oauth.tokenprovider.clientSecret}
      username: ${oauth.tokenprovider.clientId}
      password: ${oauth.tokenprovider.clientPassword}
      clientAuthenticationScheme: form
    resource:
      jwt:
        keyUri: ${oauth.tokenprovider.url}/oauth/token_key
logging:
  level:
    edu:
      iu:
        uits:
          lms:
            courselist: DEBUG
            common: DEBUG
    org:
      springframework:
        security: DEBUG

deptprov:
  version: ${app.version}

---

spring:
  profiles: redis
  session:
    store-type: redis

